name: Hello World CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: hello 1
        run: echo "Hello Naaaaa"
